name: API Tests (Newman)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install newman
        run: npm install -g newman

      - name: Start app (background)
        run: |
          npm ci
          npm run build || true
          nohup npm run start:dev &
          sleep 10

      - name: Run CURRENT collection
        run: |
          newman run ./ecommerce-api-current.postman_collection.json -e ./ecommerce-api-local.postman_environment.json --timeout-request 10000 || true

      - name: Run TARGET RUBRICA template (will fail until implemented)
        run: |
          newman run ./ecommerce-api-rubrica-template.postman_collection.json -e ./ecommerce-api-local.postman_environment.json --timeout-request 10000 || true
