name: API Tests (Newman)
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  newman:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports: ['27017:27017']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install global tools
        run: npm i -g newman
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Seed DB
        env:
          MONGODB_URI: mongodb://localhost:27017/ecommerce_api
          ADMIN_EMAIL: admin@mail.com
          ADMIN_PASSWORD: AdminPassw0rd!
        run: node -r ts-node/register -r tsconfig-paths/register src/seeds/seed.ts
      - name: Start API
        env:
          MONGODB_URI: mongodb://localhost:27017/ecommerce_api
          JWT_SECRET: supersecretjwt
          JWT_EXPIRES_IN: 1h
        run: nohup node dist/main.js & sleep 8
      - name: Run Postman compliance suite
        run: newman run ./ecommerce-api-rubrica-compliance.postman_collection.json -e ./ecommerce-api-local.postman_environment.json --timeout-request 12000
